services:
  # Backend API Service
  - type: web
    name: ifm-project-mgmt-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: CORS_ALLOWED_ORIGINS
        value: https://ifm-project-management-jqf2uyyvt-khrlawliets-projects.vercel.app
      - key: JAVA_OPTS
        value: -Xmx256m -Xms128m
